// apps/cube-tutorial/src/scripts/modules/todo-mvc/view/v-footer.tsx
import React, { useCallback } from 'react'
import clsx from 'clsx'
import { Logger } from 'wdc-cube'
import Css from './todo-mvc.module.scss'
import { bindUpdate, IViewProps } from 'wdc-cube-react'
import { FooterScope, ShowingOptions } from '../todo-mvc.scope'

const LOG = Logger.get('TodoMvc.FooterView')

type FooterViewProps = IViewProps & { scope: FooterScope }

export const FooterView = function ({ className, style, scope, scope: { actions } }: FooterViewProps) {
    LOG.debug('update')

    bindUpdate(React, scope)

    const onClearCompleted = useCallback(actions.onClearCompleted, [actions.onClearCompleted])
    const onShowAll = useCallback(actions.onShowAll, [actions.onShowAll])
    const onShowActives = useCallback(actions.onShowActives, [actions.onShowActives])
    const onShowCompleteds = useCallback(actions.onShowCompleteds, [actions.onShowCompleteds])

    let clearButton = <></>

    if (scope.clearButtonVisible) {
        clearButton = (
            <button className={Css.clearCompleted} onClick={onClearCompleted}>
                Clear completed
            </button>
        )
    }

    return (
        <footer className={clsx(className, Css.footer)} style={style}>
            <span className={Css.todoCount}>
                <strong>{scope.count}</strong> {scope.activeTodoWord} left
            </span>
            <ul className={Css.filters}>
                <li>
                    <a
                        className={clsx(scope.showing == ShowingOptions.ALL ? Css.selected : undefined)}
                        onClick={onShowAll}
                    >
                        All
                    </a>
                </li>{' '}
                <li>
                    <a
                        className={clsx(scope.showing == ShowingOptions.ACTIVE ? Css.selected : undefined)}
                        onClick={onShowActives}
                    >
                        Active
                    </a>
                </li>{' '}
                <li>
                    <a
                        className={clsx(scope.showing == ShowingOptions.COMPLETED ? Css.selected : undefined)}
                        onClick={onShowCompleteds}
                    >
                        Completed
                    </a>
                </li>
            </ul>
            {clearButton}
        </footer>
    )
}

// apps/cube-tutorial/renderer-solid/src/scripts/modules/todo-mvc/v-footer.tsx
import { For, Show, type JSX } from 'solid-js'
import type { ViewProps } from 'wdc-cube-solid'
import { FooterScope, ShowingOptions } from 'wdc-cube-tutorial-presentation/todo-mvc'

import Css from './todo-mvc.module.scss'

export function FooterView(props: ViewProps<FooterScope>): JSX.Element {
    const filters = () =>
        [
            { showing: ShowingOptions.ALL, label: 'All', select: () => props.scope.actions.onShowAll() },
            { showing: ShowingOptions.ACTIVE, label: 'Active', select: () => props.scope.actions.onShowActives() },
            {
                showing: ShowingOptions.COMPLETED,
                label: 'Completed',
                select: () => props.scope.actions.onShowCompleteds()
            }
        ] as const

    return (
        <footer class={Css.footer}>
            <span class={Css.todoCount}>
                <strong>{props.scope.count}</strong> {props.scope.activeTodoWord} left
            </span>

            <ul class={Css.filters}>
                <For each={filters()}>
                    {(filter) => (
                        <li>
                            <a
                                classList={{ [Css.selected]: props.scope.showing === filter.showing }}
                                onClick={filter.select}
                            >
                                {filter.label}
                            </a>
                        </li>
                    )}
                </For>
            </ul>

            <Show when={props.scope.clearButtonVisible}>
                <button class={Css.clearCompleted} onClick={() => props.scope.actions.onClearCompleted()}>
                    Clear completed
                </button>
            </Show>
        </footer>
    )
}
