// apps/cube-tutorial/src/scripts/modules/subscriptions/view/v-subscriptions.tsx
import React from 'react'
import clsx from 'clsx'
import { Logger } from 'wdc-cube'
import { bindUpdate, IViewProps } from 'wdc-cube-react'
import List from '@mui/material/List'
import ListItem from '@mui/material/ListItem'
import ListItemButton from '@mui/material/ListItemButton'
import ListItemText from '@mui/material/ListItemText'
import { SubscriptionsScope } from '../subscriptions.scope'
import Css from './subscriptions.module.scss'

const LOG = Logger.get('SubscriptionsView')

type SubscriptionsViewProps = IViewProps & { scope: SubscriptionsScope }

export function SubscriptionsView({ scope, className, ...props }: SubscriptionsViewProps) {
    bindUpdate(React, scope)

    LOG.debug('update')

    const itemArray = [] as React.JSX.Element[]

    for (const item of scope.sites) {
        itemArray.push(
            <ListItem key={item.id} disablePadding>
                <ListItemButton onClick={() => scope.onItemClicked(item)}>
                    <ListItemText primary={item.site} />
                </ListItemButton>
            </ListItem>
        )
    }

    return (
        <div className={clsx(className, Css.subscriptionsView)} {...props}>
            <h1>Sites you can subscribe to...</h1>
            <List component="nav" aria-label="main mailbox folders">
                {itemArray}
            </List>
        </div>
    )
}

// apps/cube-tutorial-angular/src/scripts/modules/subscriptions/v-subscriptions.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core'
import { bindScope } from 'wdc-cube-angular'
import { SubscriptionsScope } from 'wdc-cube-tutorial-core/subscriptions'

@Component({
    selector: 'v-subscriptions',
    changeDetection: ChangeDetectionStrategy.OnPush,
    styleUrl: './subscriptions.scss',
    template: `
        <div class="subscriptions-view">
            <h1>Sites you can subscribe to...</h1>
            <nav aria-label="main mailbox folders">
                <ul>
                    @for (item of scope().sites; track item.id) {
                        <li>
                            <button type="button" (click)="scope().onItemClicked(item)">{{ item.site }}</button>
                        </li>
                    }
                </ul>
            </nav>
        </div>
    `
})
export class SubscriptionsView {
    readonly scope = input.required<SubscriptionsScope>()

    constructor() {
        bindScope(this.scope)
    }
}
