// apps/cube-tutorial/renderer-solid/src/scripts/modules/todo-mvc/v-clock.tsx
import { type JSX } from 'solid-js'
import type { ViewProps } from 'wdc-cube-solid'
import { ClockScope } from 'wdc-cube-tutorial-presentation/todo-mvc'

import Css from './todo-mvc.module.scss'

export function ClockView(props: ViewProps<ClockScope>): JSX.Element {
    return (
        <li class={Css.clock}>
            <div>{props.scope.date.toLocaleTimeString()}</div>
        </li>
    )
}

// apps/cube-tutorial/src/scripts/modules/todo-mvc/view/v-clock.tsx
import React from 'react'
import clsx from 'clsx'
import { Logger } from 'wdc-cube'
import { bindUpdate, IViewProps } from 'wdc-cube-react'
import { ClockScope } from '../todo-mvc.scope'
import Css from './todo-mvc.module.scss'

const LOG = Logger.get('TodoMvc.ClockScope')

export function ClockView({ className, style, scope }: IViewProps & { scope: ClockScope }) {
    bindUpdate(React, scope)

    LOG.debug('update')

    return (
        <li className={clsx(className, Css.clock)} style={style}>
            <div>{scope.date.toLocaleTimeString()}</div>
        </li>
    )
}
