// libs/cube-angular/src/impl/ViewFactory.ts
/**
 * Copyright © 2017-2026 WeDoCode Consultoria e Soluções Avançadas LTDA.
 * Licensed under the MIT License. See LICENSE in the project root.
 *
 * Author: Marcelo Domingos
 * Source: https://github.com/mrcdom/wdc-cube
 */

import type { Type } from '@angular/core'
import { createViewRegistry, type Scope, type ScopeConstructor } from 'wdc-cube'

/** A component that draws a scope. It must accept a `scope` input. */
export type CubeViewType = Type<unknown>

const registry = createViewRegistry<CubeViewType>('wdc-cube-angular:view')

export class ViewFactory {
    /** Pairs a scope class with the component that draws it. */
    public static register(scopeCtor: ScopeConstructor, view: CubeViewType): void {
        registry.register(scopeCtor, view)
    }

    /** The component registered for this scope's class, if any. */
    public static get(scope?: Scope | null): CubeViewType | undefined {
        return registry.get(scope)
    }
}

// libs/cube-react/src/impl/ViewFactory.ts
/**
 * Copyright © 2017-2026 WeDoCode Consultoria e Soluções Avançadas LTDA.
 * Licensed under the MIT License. See LICENSE in the project root.
 *
 * Author: Marcelo Domingos
 * Source: https://github.com/mrcdom/wdc-cube
 */

import React from 'react'
import { createViewRegistry, Scope, ScopeConstructor } from 'wdc-cube'

export type IViewProps = {
    className?: string
    style?: React.CSSProperties
}

export type IViewConstructor<P extends IFactoryProps> = React.ComponentClass<P> | React.FunctionComponent<P>

type IFactoryProps = IViewProps & {
    scope?: Scope
}

type ViewSlotProps<P extends IFactoryProps, S extends Scope> = IViewProps & {
    scope?: S | null
    optional?: boolean
    style?: React.CSSProperties
    view?: IViewConstructor<P>
}

export function ViewSlot<P extends IFactoryProps, S extends Scope>({
    scope,
    optional = true,
    view,
    ...props
}: ViewSlotProps<P, S>): React.ReactElement | null {
    if (scope) {
        if (view) {
            const ctor = view as IViewConstructor<IFactoryProps>
            return React.createElement(ctor, { scope, ...props })
        }

        const ctor = ViewFactory.get(scope)
        if (ctor) {
            return React.createElement(ctor, { scope, ...props })
        }

        return React.createElement(
            'div',
            { className: props.className, style: props.style },
            `View(${scope.constructor.name}) not found!`
        )
    }

    if (!optional) {
        return React.createElement('div', {
            className: props.className,
            style: props.style
        })
    }

    return null
}

const registry = createViewRegistry<IViewConstructor<IFactoryProps>>('wdc-cube-react:view')

export class ViewFactory {
    // Static API

    public static register<P extends IFactoryProps>(scopeCtor: ScopeConstructor, viewCtor: IViewConstructor<P>): void {
        registry.register(scopeCtor, viewCtor as IViewConstructor<IFactoryProps>)
    }

    public static get(scope?: Scope): IViewConstructor<IFactoryProps> | undefined {
        return registry.get(scope)
    }

    public static createView(scope?: Scope, props?: IViewProps): React.ReactElement {
        if (props) {
            return React.createElement(ViewSlot, { scope, ...props })
        }
        return React.createElement(ViewSlot, { scope })
    }
}
