// apps/cube-tutorial/renderer-solid/src/scripts/modules/todo-mvc/v-clock.tsx
import { type JSX } from 'solid-js'
import type { ViewProps } from 'wdc-cube-solid'
import { ClockScope } from 'wdc-cube-tutorial-presentation/todo-mvc'

import Css from './todo-mvc.module.scss'

export function ClockView(props: ViewProps<ClockScope>): JSX.Element {
    return (
        <li class={Css.clock}>
            <div>{props.scope.date.toLocaleTimeString()}</div>
        </li>
    )
}

// apps/cube-tutorial/renderer-react/src/scripts/modules/todo-mvc/v-clock.tsx
import clsx from 'clsx'
import { Logger } from 'wdc-cube'
import { classToFComponent, FCClass, type IViewProps } from 'wdc-cube-react'
import { ClockScope } from 'wdc-cube-tutorial-presentation/todo-mvc'
import Css from './todo-mvc.module.scss'

const LOG = Logger.get('TodoMvc.ClockScope')

type ClockViewProps = IViewProps & { scope: ClockScope }

class ClockViewClass extends FCClass<ClockViewProps> {
    render({ className, style }: ClockViewProps) {
        LOG.debug('update')

        return (
            <li className={clsx(className, Css.clock)} style={style}>
                <div>{this.scope.date.toLocaleTimeString()}</div>
            </li>
        )
    }
}

export const ClockView = classToFComponent(ClockViewClass)
