// apps/cube-tutorial/renderer-solid/src/scripts/modules/restricted/v-restricted.tsx
import { Show, type JSX } from 'solid-js'
import { ViewSlot, type ViewProps } from 'wdc-cube-solid'
import { RestrictedScope } from 'wdc-cube-tutorial-presentation/restricted'

import Css from './restricted.module.scss'

export function RestrictedView(props: ViewProps<RestrictedScope>): JSX.Element {
    return (
        <div class={Css.restrictedView}>
            <Show when={props.scope.detail} fallback={<p>Nothing is nested under this place yet.</p>}>
                {/* The slot this presenter offers to a deeper place. Passing its
                    own scope here would resolve back to this very view. */}
                <ViewSlot scope={props.scope.detail} />
            </Show>
        </div>
    )
}

// apps/cube-tutorial-angular/src/scripts/modules/restricted/v-restricted.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core'
import { bindScope, CubeViewSlot } from 'wdc-cube-angular'
import { RestrictedScope } from 'wdc-cube-tutorial-core/restricted'

@Component({
    selector: 'v-restricted',
    changeDetection: ChangeDetectionStrategy.OnPush,
    imports: [CubeViewSlot],
    styles: `
        .restricted-view {
            display: flex;
            background-color: rgb(255, 0, 242);
        }
    `,
    template: `
        <div class="restricted-view">
            @if (scope().detail) {
                <!-- The slot this presenter offers to a deeper place. Passing
                     scope() here would resolve back to this very view. -->
                <ng-container *cubeViewSlot="scope().detail"></ng-container>
            } @else {
                <p>Nothing is nested under this place yet.</p>
            }
        </div>
    `
})
export class RestrictedView {
    readonly scope = input.required<RestrictedScope>()

    constructor() {
        bindScope(this.scope)
    }
}
