// apps/cube-tutorial-react/src/scripts/modules/todo-mvc/v-footer.tsx
import clsx from 'clsx'
import { Logger } from 'wdc-cube'
import { classToFComponent, FCClass, type IViewProps } from 'wdc-cube-react'
import Css from './todo-mvc.module.scss'
import { FooterScope, ShowingOptions } from 'wdc-cube-tutorial-core/todo-mvc'

const LOG = Logger.get('TodoMvc.FooterView')

type FooterViewProps = IViewProps & { scope: FooterScope }

class FooterViewClass extends FCClass<FooterViewProps> {
    private readonly onClearCompleted = () => this.scope.actions.onClearCompleted()
    private readonly onShowAll = () => this.scope.actions.onShowAll()
    private readonly onShowActives = () => this.scope.actions.onShowActives()
    private readonly onShowCompleteds = () => this.scope.actions.onShowCompleteds()

    render({ className, style }: FooterViewProps) {
        LOG.debug('update')

        const scope = this.scope

        return (
            <footer className={clsx(className, Css.footer)} style={style}>
                <span className={Css.todoCount}>
                    <strong>{scope.count}</strong> {scope.activeTodoWord} left
                </span>
                <ul className={Css.filters}>
                    <li>
                        <a
                            className={clsx(scope.showing == ShowingOptions.ALL ? Css.selected : undefined)}
                            onClick={this.onShowAll}
                        >
                            All
                        </a>
                    </li>{' '}
                    <li>
                        <a
                            className={clsx(scope.showing == ShowingOptions.ACTIVE ? Css.selected : undefined)}
                            onClick={this.onShowActives}
                        >
                            Active
                        </a>
                    </li>{' '}
                    <li>
                        <a
                            className={clsx(scope.showing == ShowingOptions.COMPLETED ? Css.selected : undefined)}
                            onClick={this.onShowCompleteds}
                        >
                            Completed
                        </a>
                    </li>
                </ul>
                {scope.clearButtonVisible ? (
                    <button className={Css.clearCompleted} onClick={this.onClearCompleted}>
                        Clear completed
                    </button>
                ) : null}
            </footer>
        )
    }
}

export const FooterView = classToFComponent(FooterViewClass)

// apps/cube-tutorial-angular/src/scripts/modules/todo-mvc/v-footer.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core'
import { bindScope } from 'wdc-cube-angular'
import { FooterScope, ShowingOptions } from 'wdc-cube-tutorial-core/todo-mvc'

@Component({
    selector: 'v-footer',
    changeDetection: ChangeDetectionStrategy.OnPush,
    styleUrl: './todo-mvc.scss',
    template: `
        <footer class="footer">
            <span class="todo-count">
                <strong>{{ scope().count }}</strong> {{ scope().activeTodoWord }} left
            </span>
            <ul class="filters">
                <li>
                    <a [class.selected]="scope().showing === Showing.ALL" (click)="scope().actions.onShowAll()">All</a>
                </li>
                <li>
                    <a [class.selected]="scope().showing === Showing.ACTIVE" (click)="scope().actions.onShowActives()">
                        Active
                    </a>
                </li>
                <li>
                    <a
                        [class.selected]="scope().showing === Showing.COMPLETED"
                        (click)="scope().actions.onShowCompleteds()"
                    >
                        Completed
                    </a>
                </li>
            </ul>
            @if (scope().clearButtonVisible) {
                <button type="button" class="clear-completed" (click)="scope().actions.onClearCompleted()">
                    Clear completed
                </button>
            }
        </footer>
    `
})
export class FooterView {
    readonly scope = input.required<FooterScope>()

    readonly Showing = ShowingOptions

    constructor() {
        bindScope(this.scope)
    }
}
