// apps/cube-tutorial-angular/src/scripts/modules/main/v-alert.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core'
import { bindScope } from 'wdc-cube-angular'
import { AlertScope } from 'wdc-cube-tutorial-core/main'

@Component({
    selector: 'v-alert',
    changeDetection: ChangeDetectionStrategy.OnPush,
    styleUrl: './main.scss',
    template: `
        <div class="alert alert-{{ scope().severity }}" role="alert">
            <strong class="alert-title">{{ scope().title }}</strong>
            <p>{{ scope().message }}</p>
        </div>
        <div class="dialog-actions">
            <button type="button" (click)="scope().onClose()">Close</button>
        </div>
    `
})
export class AlertView {
    readonly scope = input.required<AlertScope>()

    constructor() {
        bindScope(this.scope)
    }
}

// apps/cube-tutorial/src/scripts/modules/main/view/v-alert.tsx
import React, { useCallback } from 'react'
import clsx from 'clsx'
import Button from '@mui/material/Button'
import Alert from '@mui/material/Alert'
import AlertTitle from '@mui/material/AlertTitle'
import DialogActions from '@mui/material/DialogActions'
import DialogContentText from '@mui/material/DialogContentText'
import { Logger } from 'wdc-cube'
import { bindUpdate, IViewProps } from 'wdc-cube-react'
import { AlertScope } from '../main.scope'
import Css from './main.module.scss'

const LOG = Logger.get('Main.AlertView')

export type AlertViewProps = IViewProps & {
    scope: AlertScope
}

export function AlertView({ scope, className, ...props }: AlertViewProps) {
    bindUpdate(React, scope)

    LOG.debug('update')

    const onClose = useCallback(scope.onClose, [scope.onClose])

    return (
        <>
            <Alert className={clsx(className, Css.AlertPane)} severity={scope.severity} {...props}>
                <AlertTitle>{scope.title}</AlertTitle>
                <DialogContentText>{scope.message}</DialogContentText>
            </Alert>
            <DialogActions>
                <Button onClick={onClose} color="primary">
                    Close
                </Button>
            </DialogActions>
        </>
    )
}
